config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :user_stocks, only:[:create, :destroy]
  root 'welcomes#index'
  get 'my_portfolio', to:"users#my_portfolio"
  get 'search_stock', to:"stocks#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence:true
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
        publishable_token: 'Tpk_b51e69522bab4742b8413a76618c534e',
        endpoint: 'https://sandbox.iexapis.com/v1' )
    client.price(ticker_symbol)
    begin
    new(ticker:ticker_symbol,name:client.company(ticker_symbol).company_name,last_price:client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_ticker_in_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
        if params[:stock].present?
    @stock = Stock.new_lookup(params[:stock])
        if @stock
          respond_to do |format|
            format.js {render partial:'users/result'}
          end
        else
          respond_to do |format|
            flash[:alert] = "please enter a valid symbol"
            format.js {render partial:'users/result'}
          end
          end
    else
      respond_to do |format|
        flash[:alert] = "please enter a symbol"
        format.js{render partial: 'users/result'}
      end
        end

end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_ticker_in_db(params[:ticker])
    if stock.blank?
    stock = Stock.new_lookup(params[:ticker])
    stock.save
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added in my portfolio"
    redirect_to my_portfolio_path

    else
      flash[:alert] = "ticker already in stock"
      redirect_to my_portfolio_path
    end
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully deleted"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @tracked_stocks =  current_user.stocks
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_messages.html.erb
<% if notice  %>
<div class="alert alert-success articlecle">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="alert-heading"><%=notice%></h4>
</div>
  <%end %>
<%if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <ul class="mb-0"><%=alert %></ul>
  </div>
  <%end %>
<!--  <p class="notice"><%#=  %></p>-->
<!--  <p class="alert"><%#=  %></p>-->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
<h2><%=link_to 'FinanceTracker',root_path, class:"navbar-brand font-weight-bold"%></h2>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%if signed_in? %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%=link_to 'My Portfolio', my_portfolio_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <%=link_to 'Log out', destroy_user_session_path, method: :delete, class:"btn btn-danger ml-4"%>
  </div>
  <%end %>

    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%=render 'layouts/navigation' %>

  <div class="container">
    <%=render 'layouts/messages' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/stock/_list.html.erb
<% if !@tracked_stocks.empty? %>

  <div class="row">
    <div class="col-9">
      <table class="table table-hover">
        <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <%@tracked_stocks.each do|stock| %>
          <tr>
            <th scope="row"><%=stock.ticker %></th>
            <td><%=stock.name %></td>
            <td><%=stock.last_price %></td>
            <td><%=link_to "Remove", user_stock_path(stock), method: :delete, data:{confirm:"Are you sure"} %></td>
          </tr>

        <%end %>

        </tbody>
      </table>

    </div>
  </div>
<%end %>

app/views/users/_result.html.erb
<%=render 'layouts/messages' %>
<%if @stock %>


  <div class="card card-header d-inline-block">
    <strong>Symbol:</strong><%=@stock.ticker %>
    <strong>Name:</strong><%=@stock.name %>
    <strong>Price:</strong><%=@stock.last_price %>
    <%=link_to 'Add to my portflio', user_stocks_path(user:current_user, ticker: @stock.ticker),
               class:"btn btn-success hover ml-2", method: :post %>

  </div>

<%end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML =  "<%= escape_javascript(render 'users/result.html') %>"

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>


<div class="search-area">
  <h3>Search Stocks</h3>
  <p>Search symbol used in stock market like: AMZN symbol used for AMAZON in stock market</p>
  <%=form_tag search_stock_path, remote:true,  method: :get do %>
  <div class="form-group row">
    <div class="col-sm-9">
      <%= text_field_tag :stock, params[:stock], placeholder:"Stock ticker symbol",autofocus:true,
                         :required => true,
                         class:"form-control from-control-lg"%>
    </div>
    <div class="col-sm-3">
      <%=button_tag type: :submit, class:"btn btn-success" do%>
      <%= 'Search' %>
      <%end %>
    </div>
  </div>
  <% end %>
</div>

<div class="d-block mb-3">
<div id="results">
</div>
</div>



<%= render "stock/list" %>

app/views/welcomes/index.html.erb
<h1>welcome Finance Tracker app</h1>

<%=link_to 'sign out', destroy_user_session_path, method: :delete %>